[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "CONFIGLIB_ADMINS,CONFIGLIB_SECRET"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/save-parts"
  to = "/.netlify/functions/save-parts"
  status = 200

[[redirects]]
  from = "/api/get-parts"
  to = "/.netlify/functions/get-parts"
  status = 200
